### ISSUE TITLE
When I put in a SoundCloud link in the etching table on my modded server with create and etched on it does not work 

### ISSUE THREAD

**Issue by ghost** [MoonflowerTeam/etched#12]
I have a modded server with create and etched on it but when I try to make a disk and put in a SoundCloud link it does not work. #12

**Comment by AllSuperHeroes** [comment]
apparently, the etched mod file is not working on the server-side of things can someone help

**Comment by ghost** [comment]
Here is the list of all the mods on the server currently, I removed etched from the server because of the bug

[1.16.5]+SecurityCraft+v1.8.23.jar
abnormals_core-1.16.5-3.2.0.jar 
Aquaculture-1.16.5-2.1.20.jar  
backpacked-1.10.1-1.16.3.jar 
catalogue-1.3.0-1.16.5.jar 
cfm-7.0.0pre22-1.16.3.jar 
cgm-1.0.1-1.16.3.jar 
create-mc1.16.5_v0.3.2d.jar 
dungeons_gear-1.16.5-3.0.17.jar 
flywheel-1.16-0.2.3.jar  
immersive-portals-0.16-mc1.16.5-forge.jar  
Mantle-1.16.5-1.6.123.jar
mcw-doors-1.0.3-mc1.16.5.jar 
obfuscate-0.6.2-1.16.3.jar
Pehkui-2.3.0+1.16.5-forge.jar 
pillagersplus-1.16.3-1.0.1.jar 
secretrooms-1.16.5-1.1.2.jar 
TConstruct-1.16.5-3.1.2.265.jar 
timeless_and_classic_4.0.0_RELEASE.jar  
upgrade_aquatic-1.16.5-3.1.0.jar
vehicle-mod-0.45.2-1.16.3.jar
worldedit-mod-7.2.5-dist.jar

**Comment by jacksonhardaway** [comment]
Please provide your latest.log from the server

**Comment by ph0l** [comment]
Hi, I've been playing with it, the same problem
found something tho, in console (while playing)
there you go:

[18:14:24] [Downloader 6/INFO]: Retrieving sound cloud id
[18:14:24] [Downloader 6/INFO]: [me.jaackson.etched.common.menu.EtchingMenu:lambda$setupResultSlot$3:367]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[18:14:24] [Downloader 6/INFO]: [me.jaackson.etched.common.menu.EtchingMenu:lambda$setupResultSlot$3:367]: 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[18:14:24] [Downloader 6/INFO]: [me.jaackson.etched.common.menu.EtchingMenu:lambda$setupResultSlot$3:367]: 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[18:14:24] [Downloader 6/INFO]: [me.jaackson.etched.common.menu.EtchingMenu:lambda$setupResultSlot$3:367]: 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584)
[18:14:24] [Downloader 6/INFO]: [me.jaackson.etched.common.menu.EtchingMenu:lambda$setupResultSlot$3:367]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:14:24] [Downloader 6/INFO]: [me.jaackson.etched.common.menu.EtchingMenu:lambda$setupResultSlot$3:367]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:14:24] [Downloader 6/INFO]: [me.jaackson.etched.common.menu.EtchingMenu:lambda$setupResultSlot$3:367]: 	at java.lang.Thread.run(Thread.java:745)
[18:14:24] [Downloader 6/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
